### ISSUE TITLE
特定の文字が含まれているとデバッグモードでクラッシュする

### ISSUE THREAD

**Issue by osak** [toshia/mikutter-sub-parts-client#9]
特定の文字（💻）がクライアント名に含まれているツイートを表示しようとしたとき、mikutterがデバッグモードで走っているとクラッシュします。以下は[クライアント名が「💻twterm」であるツイート](https://twitter.com/ryotakameoka/status/1223094356128624640)を表示した時のエラーメッセージです。
<pre>
error: {MIKUTTER_DIR}/core/mui/cairo_cell_renderer_message.rb:132:in `rescue in uri=': Cairo::InvalidMatrixError by uri: https://twitter.com/ryotakameoka/status/1223094356128624640 model: #<Plugin::Twitter::Message: 1223094356128624640 TwitterUser(@ryotakameoka) 今日の京都寒すぎて Sumthin' Sumthin'!! って思ってたら北方の山々に雪が積もっていた．南無．>
notice: {MIKUTTER_DIR}/core/serialthread.rb:48:in `force_exit!': all Serial Thread Group jobs canceled.
notice: mikutter.rb:93:in `boot!': raise mainloop exception `Cairo::InvalidMatrixError'
notice: mikutter.rb:98:in `error_handling!': catch Cairo::InvalidMatrixError
Traceback (most recent call last):
        15: from mikutter.rb:117:in `<main>'
        14: from mikutter.rb:81:in `boot!'
        13: from /home/osamu/app/mikutter/plugin/gtk/mainloop.rb:10:in `mainloop'
        12: from /home/osamu/app/mikutter/plugin/gtk/mainloop.rb:10:in `catch'
        11: from /home/osamu/app/mikutter/plugin/gtk/mainloop.rb:12:in `block in mainloop'
        10: from /home/osamu/app/mikutter/plugin/gtk/mainloop.rb:12:in `loop'
         9: from /home/osamu/app/mikutter/plugin/gtk/mainloop.rb:18:in `block (2 levels) in mainloop'
         8: from /home/osamu/app/mikutter/plugin/gtk/mainloop.rb:18:in `main_iteration'
         7: from /home/osamu/app/mikutter/core/mui/cairo_cell_renderer_message.rb:128:in `uri='
         6: from /home/osamu/app/mikutter/core/mui/cairo_cell_renderer_message.rb:149:in `render_message'
         5: from /home/osamu/app/mikutter/core/mui/cairo_miracle_painter.rb:126:in `pixbuf'
         4: from /home/osamu/app/mikutter/core/mui/cairo_miracle_painter.rb:458:in `gen_pixbuf'
         3: from /home/osamu/app/mikutter/core/mui/cairo_miracle_painter.rb:445:in `gen_pixmap'
         2: from /home/osamu/app/mikutter/core/mui/cairo_miracle_painter.rb:484:in `render_to_context'
         1: from /home/osamu/app/mikutter/core/mui/cairo_sub_parts_helper.rb:25:in `render_parts'
/home/osamu/app/mikutter/core/mui/cairo_sub_parts_helper.rb:25:in `save': invalid matrix (not invertible) (Cairo::InvalidMatrixError)
bundle exec ruby mikutter.rb --debug  1327.84s user 85.07s system 0% cpu 70:41:54.25 total
</pre>

デバッグモードではないときには以下のエラーメッセージが出て、クライアント名は豆腐になります。このときはクラッシュしません。
<pre>
Pango-WARNING **: shaping failure, expect ugly output. shape-engine='PangoFcShapeEngine', font='Noto Color Emoji', text='💻'
        from /home/osamu/.gem/gems/gobject-introspection-3.4.1/lib/gobject-introspection/loader.rb:600:in `invoke'
        from /home/osamu/.gem/gems/gobject-introspection-3.4.1/lib/gobject-introspection/loader.rb:514:in `block in define_method'
        from /home/osamu/.mikutter/plugin/sub_parts_client/sub_parts_client.rb:25:in `block in render'
        from /home/osamu/.mikutter/plugin/sub_parts_client/sub_parts_client.rb:23:in `save'
        from /home/osamu/.mikutter/plugin/sub_parts_client/sub_parts_client.rb:23:in `render'
        from /home/osamu/app/mikutter/core/mui/cairo_sub_parts_helper.rb:30:in `block (3 levels) in render_parts'
        from /home/osamu/app/mikutter/core/mui/cairo_sub_parts_helper.rb:29:in `save'
        from /home/osamu/app/mikutter/core/mui/cairo_sub_parts_helper.rb:29:in `block (2 levels) in render_parts'
        from /home/osamu/app/mikutter/core/mui/cairo_sub_parts_helper.rb:28:in `each'
        from /home/osamu/app/mikutter/core/mui/cairo_sub_parts_helper.rb:28:in `block in render_parts'
        from /home/osamu/app/mikutter/core/mui/cairo_sub_parts_helper.rb:25:in `save'
        from /home/osamu/app/mikutter/core/mui/cairo_sub_parts_helper.rb:25:in `render_parts'
        from /home/osamu/app/mikutter/core/mui/cairo_miracle_painter.rb:484:in `render_to_context'
        from /home/osamu/app/mikutter/core/mui/cairo_miracle_painter.rb:445:in `gen_pixmap'
        from /home/osamu/app/mikutter/core/mui/cairo_miracle_painter.rb:458:in `gen_pixbuf'
        from /home/osamu/app/mikutter/core/mui/cairo_miracle_painter.rb:126:in `pixbuf'
        from /home/osamu/app/mikutter/core/mui/cairo_cell_renderer_message.rb:149:in `render_message'
        from /home/osamu/app/mikutter/core/mui/cairo_cell_renderer_message.rb:128:in `uri='
        from /home/osamu/app/mikutter/plugin/gtk/mainloop.rb:18:in `main_iteration'
        from /home/osamu/app/mikutter/plugin/gtk/mainloop.rb:18:in `block (2 levels) in mainloop'
        from /home/osamu/app/mikutter/plugin/gtk/mainloop.rb:12:in `loop'
        from /home/osamu/app/mikutter/plugin/gtk/mainloop.rb:12:in `block in mainloop'
        from /home/osamu/app/mikutter/plugin/gtk/mainloop.rb:10:in `catch'
        from /home/osamu/app/mikutter/plugin/gtk/mainloop.rb:10:in `mainloop'
        from mikutter.rb:81:in `boot!'
        from mikutter.rb:117:in `<main>'
</pre>

そもそも最近、このプラグインを入れてもクライアント名が表示されなくなっているようなので、もっと深い問題の一部なのかもしれません。

**Comment by tsutsui** [comment]
> そもそも最近、このプラグインを入れてもクライアント名が表示されなくなっているようなので、もっと深い問題の一部なのかもしれません。

別チケットで書け案件ですが
0.0.3 以前から使って使っている秘伝のタレ状態のメインマシンだとクライアント名表示されるのに、3.9.9くらいから入れたレッツノートだとクライアント名が出ない、という謎の状態になってます……

**Comment by toshia** [comment]
クライアント名が出ないのは私の環境でも再現していませんが、どこかで聞いた覚えはある気がします。どういう条件なんでしょうね。
